# Cleaning Clinical Datasets and Applying HIPAA De-Identification

Time estimate: **20** minutes

## Objectives
After completing this lab, you will be able to:
- Identify and remove duplicate clinical records.  
- Correct invalid or inconsistent clinical values.  
- Handle missing data using appropriate strategies.  
- Detect and review potential outliers.  
- Apply HIPAA Safe Harbor de-identification rules.

## What you will do in this lab
In this lab, you will work with a synthetic clinical dataset to clean, prepare, and de-identify healthcare data for safe analysis.

You will:

- Load and inspect a synthetic clinical dataset.  
- Clean duplicate and invalid records.  
- Address missing values in key fields.  
- Identify potential outliers in clinical measurements.  
- De-identify the dataset using HIPAA Safe Harbor rules.

## Overview
Clinical datasets often contain data quality issues such as duplicates, invalid values,
and missing information. In addition, healthcare data must be handled carefully to
protect patient privacy. This lab focuses on practical data cleaning techniques while
also applying HIPAA Safe Harbor de-identification rules to produce a privacy-compliant,
analysis-ready dataset.

## About the dataset/environment
You will work with a **synthetic clinical dataset** that includes patient demographics,
visit information, and vital signs. The dataset intentionally contains duplicates,
invalid entries, missing values, outliers, and identifiable information such as names
and dates. These issues simulate real-world healthcare data challenges.

## Setup

In [1]:

# This cell imports required libraries and loads a synthetic clinical dataset.


import pandas as pd
import numpy as np

# Load a synthetic clinical dataset
clinical_df = pd.read_csv("https://fundamentals-of-healthcare-data-science-858397.gitlab.io/labs/lab4/clinical_data_quality_lab_dataset.csv")

# Convert date columns to datetime
clinical_df["date_of_birth"] = pd.to_datetime(clinical_df["date_of_birth"])
clinical_df["visit_date"] = pd.to_datetime(clinical_df["visit_date"])

# Display the top 5 rows in the dataset
clinical_df.head()

  patient_id   patient_name date_of_birth visit_date  heart_rate  systolic_bp
0      P0373  Patient_P0373    1975-01-15 2023-01-18          82        132.0
1      P0280  Patient_P0280    1957-05-04 2023-01-13          45        124.0
2      P0228  Patient_P0228    1971-06-17 2023-01-09          54        108.0
3      P0196  Patient_P0196    1982-12-19 2023-01-10          77        114.0
4      P0229  Patient_P0229    1987-07-10 2023-01-17          71        152.0

## Step 1: Identify duplicate records
You will start by checking whether the same clinical record appears more than once.
Duplicate records are common in healthcare systems due to data entry or system issues.

**Why this matters in healthcare:** Duplicate records can inflate patient counts and distort clinical metrics.

In [2]:
# Print the number of rows and columns in the dataset.
print(f"Number of rows: {clinical_df.shape[0]}")
print(f"Number of columns: {clinical_df.shape[1]}")

Number of rows: 2100
Number of columns: 6

In [3]:

# Detecting duplicates is the first step in cleaning clinical data.
# This cell identifies duplicate rows in the dataset.


# Count the number of  duplicate rows
print(clinical_df.duplicated().sum())

100

In [4]:

# Print the duplicate rows
clinical_df[clinical_df.duplicated()]

,patient_id,patient_name,date_of_birth,visit_date,heart_rate,systolic_bp
194,P0118,Patient_P0118,1985-07-14,2023-01-29,93,123.0
200,P0293,Patient_P0293,1948-02-24,2023-01-19,90,135.0
208,P0368,Patient_P0368,1995-07-22,2023-01-12,84,121.0
227,P0255,Patient_P0255,1982-09-05,2023-01-04,54,143.0
251,P0385,Patient_P0385,1988-08-13,2023-01-10,113,132.0
...,...,...,...,...,...,...
2049,P0181,Patient_P0181,1957-06-20,2023-01-29,52,144.0
2064,P0149,Patient_P0149,1980-08-22,2023-01-06,58,NaN
2066,P0026,Patient_P0026,2001-04-03,2023-01-20,98,98.0
2069,P0291,Patient_P0291,1996-09-26,2023-01-11,94,140.0
2078,P0324,Patient_P0324,2002-06-17,2023-01-25,70,109.0

## Step 2: Remove duplicate records
After identifying duplicates, you will remove them to ensure each record is counted once.

**Why this matters in healthcare:** Removing duplicates prevents over-counting patients and visits.

In [5]:

# This cell removes duplicate rows from the dataset.
# Deduplication ensures accurate analysis.

clinical_df_deduped = clinical_df.drop_duplicates().copy()
clinical_df_deduped

,patient_id,patient_name,date_of_birth,visit_date,heart_rate,systolic_bp
0,P0373,Patient_P0373,1975-01-15,2023-01-18,82,132.0
1,P0280,Patient_P0280,1957-05-04,2023-01-13,45,124.0
2,P0228,Patient_P0228,1971-06-17,2023-01-09,54,108.0
3,P0196,Patient_P0196,1982-12-19,2023-01-10,77,114.0
4,P0229,Patient_P0229,1987-07-10,2023-01-17,71,152.0
...,...,...,...,...,...,...
2095,P0375,Patient_P0375,1952-04-27,2023-01-08,90,119.0
2096,P0319,Patient_P0319,1956-12-01,2023-01-19,65,175.0
2097,P0243,Patient_P0243,1963-03-03,2023-01-23,51,153.0
2098,P0016,Patient_P0016,1997-08-04,2023-01-20,-15,129.0
2099,P0233,Patient_P0233,1947-11-12,2023-01-10,65,NaN

## Step 3: Correct invalid clinical values
Next, you will look for values that do not make clinical sense, such as negative heart rates.

**Why this matters in healthcare:** Invalid clinical values can lead to unsafe or misleading conclusions.

In [6]:

# This cell corrects invalid clinical values.
# Cleaning invalid values improves data reliability.

# Replace negative heart rates with NaN (Not a Number)
clinical_df_deduped.loc[clinical_df_deduped["heart_rate"] < 0, "heart_rate"] = np.nan

clinical_df_deduped

,patient_id,patient_name,date_of_birth,visit_date,heart_rate,systolic_bp
0,P0373,Patient_P0373,1975-01-15,2023-01-18,82.0,132.0
1,P0280,Patient_P0280,1957-05-04,2023-01-13,45.0,124.0
2,P0228,Patient_P0228,1971-06-17,2023-01-09,54.0,108.0
3,P0196,Patient_P0196,1982-12-19,2023-01-10,77.0,114.0
4,P0229,Patient_P0229,1987-07-10,2023-01-17,71.0,152.0
...,...,...,...,...,...,...
2095,P0375,Patient_P0375,1952-04-27,2023-01-08,90.0,119.0
2096,P0319,Patient_P0319,1956-12-01,2023-01-19,65.0,175.0
2097,P0243,Patient_P0243,1963-03-03,2023-01-23,51.0,153.0
2098,P0016,Patient_P0016,1997-08-04,2023-01-20,NaN,129.0
2099,P0233,Patient_P0233,1947-11-12,2023-01-10,65.0,NaN

## Step 4: Handle missing values
Clinical data often contains missing measurements.
Here, you will apply a simple and commonly used strategy, median imputation, to handle missing values.

**Why this matters in healthcare:** Improper handling of missing data can bias results.

In [7]:

# This cell handles missing values in clinical measurements.
# Filling or flagging missing values is a common cleaning step.

# Fill missing systolic blood pressure with median
median_bp = clinical_df_deduped["systolic_bp"].median()
clinical_df_deduped["systolic_bp"] = clinical_df_deduped["systolic_bp"].fillna(median_bp)

clinical_df_deduped

,patient_id,patient_name,date_of_birth,visit_date,heart_rate,systolic_bp
0,P0373,Patient_P0373,1975-01-15,2023-01-18,82.0,132.0
1,P0280,Patient_P0280,1957-05-04,2023-01-13,45.0,124.0
2,P0228,Patient_P0228,1971-06-17,2023-01-09,54.0,108.0
3,P0196,Patient_P0196,1982-12-19,2023-01-10,77.0,114.0
4,P0229,Patient_P0229,1987-07-10,2023-01-17,71.0,152.0
...,...,...,...,...,...,...
2095,P0375,Patient_P0375,1952-04-27,2023-01-08,90.0,119.0
2096,P0319,Patient_P0319,1956-12-01,2023-01-19,65.0,175.0
2097,P0243,Patient_P0243,1963-03-03,2023-01-23,51.0,153.0
2098,P0016,Patient_P0016,1997-08-04,2023-01-20,NaN,129.0
2099,P0233,Patient_P0233,1947-11-12,2023-01-10,65.0,125.0

## Step 5: Detect potential outliers
You will now review clinical measurements to identify unusually high or low values.

**Why this matters in healthcare:** Outliers might indicate data errors or rare but important clinical events.

In [8]:

# This cell identifies potential outliers using simple thresholds.
# Outlier detection supports data quality review.

# Flag extremely high heart rates
clinical_df_deduped["heart_rate_outlier"] = clinical_df_deduped["heart_rate"] > 180

clinical_df_deduped

,patient_id,patient_name,date_of_birth,visit_date,heart_rate,systolic_bp,heart_rate_outlier
0,P0373,Patient_P0373,1975-01-15,2023-01-18,82.0,132.0,False
1,P0280,Patient_P0280,1957-05-04,2023-01-13,45.0,124.0,False
2,P0228,Patient_P0228,1971-06-17,2023-01-09,54.0,108.0,False
3,P0196,Patient_P0196,1982-12-19,2023-01-10,77.0,114.0,False
4,P0229,Patient_P0229,1987-07-10,2023-01-17,71.0,152.0,False
...,...,...,...,...,...,...,...
2095,P0375,Patient_P0375,1952-04-27,2023-01-08,90.0,119.0,False
2096,P0319,Patient_P0319,1956-12-01,2023-01-19,65.0,175.0,False
2097,P0243,Patient_P0243,1963-03-03,2023-01-23,51.0,153.0,False
2098,P0016,Patient_P0016,1997-08-04,2023-01-20,NaN,129.0,False
2099,P0233,Patient_P0233,1947-11-12,2023-01-10,65.0,125.0,False

## Step 6: Apply HIPAA Safe Harbor de-identification
Finally, you will remove or transform direct identifiers to comply with HIPAA Safe Harbor rules.

**Why this matters in healthcare:** De-identification is required to protect patient privacy and enable data sharing.

In [9]:

# This cell applies HIPAA Safe Harbor de-identification.
# Removing direct identifiers helps protect patient privacy.

# Drop direct identifiers
deidentified_df = clinical_df_deduped.drop(columns=["patient_name"])

# Generalize dates to year only
deidentified_df["birth_year"] = deidentified_df["date_of_birth"].dt.year
deidentified_df["visit_year"] = deidentified_df["visit_date"].dt.year

# Drop original date columns
deidentified_df = deidentified_df.drop(columns=["date_of_birth", "visit_date"])

deidentified_df

,patient_id,heart_rate,systolic_bp,heart_rate_outlier,birth_year,visit_year
0,P0373,82.0,132.0,False,1975,2023
1,P0280,45.0,124.0,False,1957,2023
2,P0228,54.0,108.0,False,1971,2023
3,P0196,77.0,114.0,False,1982,2023
4,P0229,71.0,152.0,False,1987,2023
...,...,...,...,...,...,...
2095,P0375,90.0,119.0,False,1952,2023
2096,P0319,65.0,175.0,False,1956,2023
2097,P0243,51.0,153.0,False,1963,2023
2098,P0016,NaN,129.0,False,1997,2023
2099,P0233,65.0,125.0,False,1947,2023

## Exercises

In [10]:
# Load the dataset for exercises
# Load a synthetic clinical dataset
clinical_df = pd.read_csv("https://fundamentals-of-healthcare-data-science-858397.gitlab.io/labs/lab4/clinical_data_quality_lab_dataset_exercises.csv")
clinical_df["date_of_birth"] = pd.to_datetime(clinical_df["date_of_birth"])
clinical_df["visit_date"] = pd.to_datetime(clinical_df["visit_date"])
clinical_df.head()

  patient_id   patient_name date_of_birth visit_date  heart_rate  systolic_bp
0      P0090  Patient_P0090    1995-06-17 2023-02-26          92        127.0
1      P0120  Patient_P0120    1987-01-18 2023-02-08         106        280.0
2      P0384  Patient_P0384    1989-01-12 2023-02-04          72        112.0
3      P0088  Patient_P0088    1944-04-20 2023-02-02          78        110.0
4      P0100  Patient_P0100    1959-10-13 2023-02-21          59        106.0

### Exercise 1: Identify duplicates

In [11]:
# your code goes here

clinical_df[clinical_df.duplicated()]

,patient_id,patient_name,date_of_birth,visit_date,heart_rate,systolic_bp
76,P0302,Patient_P0302,2000-09-17,2023-02-12,80,141.0
85,P0448,Patient_P0448,1979-03-12,2023-02-05,71,112.0
183,P0425,Patient_P0425,1981-07-19,2023-02-16,69,320.0
206,P0347,Patient_P0347,1979-04-27,2023-02-07,99,113.0
230,P0065,Patient_P0065,1958-06-15,2023-02-09,102,111.0
...,...,...,...,...,...,...
2061,P0232,Patient_P0232,1980-11-12,2023-02-18,97,125.0
2067,P0253,Patient_P0253,1992-02-14,2023-02-11,104,120.0
2091,P0230,Patient_P0230,1941-02-21,2023-02-11,74,140.0
2101,P0362,Patient_P0362,1971-07-20,2023-02-27,48,125.0
2103,P0228,Patient_P0228,1972-03-14,2023-02-22,83,146.0

### Exercise 2: Remove duplicates

In [13]:
# your code goes here
clinical_df_deduped = clinical_df_deduped.drop_duplicates().copy()
clinical_df

,patient_id,patient_name,date_of_birth,visit_date,heart_rate,systolic_bp
0,P0090,Patient_P0090,1995-06-17,2023-02-26,92,127.0
1,P0120,Patient_P0120,1987-01-18,2023-02-08,106,280.0
2,P0384,Patient_P0384,1989-01-12,2023-02-04,72,112.0
3,P0088,Patient_P0088,1944-04-20,2023-02-02,78,110.0
4,P0100,Patient_P0100,1959-10-13,2023-02-21,59,106.0
...,...,...,...,...,...,...
2115,P0085,Patient_P0085,1999-04-12,2023-02-27,78,98.0
2116,P0043,Patient_P0043,1957-12-23,2023-02-21,70,138.0
2117,P0266,Patient_P0266,1969-11-23,2023-02-01,79,112.0
2118,P0440,Patient_P0440,1953-02-14,2023-02-08,106,123.0
2119,P0416,Patient_P0416,1953-10-13,2023-02-09,0,127.0

### Exercise 3: Fix invalid values

In [14]:
# your code goes here

clinical_df_deduped.loc[clinical_df_deduped["heart_rate"] < 0, "heart_rate"] = np.nan
clinical_df_deduped

,patient_id,patient_name,date_of_birth,visit_date,heart_rate,systolic_bp,heart_rate_outlier
0,P0373,Patient_P0373,1975-01-15,2023-01-18,82.0,132.0,False
1,P0280,Patient_P0280,1957-05-04,2023-01-13,45.0,124.0,False
2,P0228,Patient_P0228,1971-06-17,2023-01-09,54.0,108.0,False
3,P0196,Patient_P0196,1982-12-19,2023-01-10,77.0,114.0,False
4,P0229,Patient_P0229,1987-07-10,2023-01-17,71.0,152.0,False
...,...,...,...,...,...,...,...
2095,P0375,Patient_P0375,1952-04-27,2023-01-08,90.0,119.0,False
2096,P0319,Patient_P0319,1956-12-01,2023-01-19,65.0,175.0,False
2097,P0243,Patient_P0243,1963-03-03,2023-01-23,51.0,153.0,False
2098,P0016,Patient_P0016,1997-08-04,2023-01-20,NaN,129.0,False
2099,P0233,Patient_P0233,1947-11-12,2023-01-10,65.0,125.0,False

### Exercise 4: Handle missing values

In [15]:
# your code goes here

median_bp = clinical_df_deduped["systolic_bp"].median()
clinical_df_deduped["systolic_bp"] = clinical_df_deduped["systolic_bp"].fillna(median_bp)

clinical_df_deduped

,patient_id,patient_name,date_of_birth,visit_date,heart_rate,systolic_bp,heart_rate_outlier
0,P0373,Patient_P0373,1975-01-15,2023-01-18,82.0,132.0,False
1,P0280,Patient_P0280,1957-05-04,2023-01-13,45.0,124.0,False
2,P0228,Patient_P0228,1971-06-17,2023-01-09,54.0,108.0,False
3,P0196,Patient_P0196,1982-12-19,2023-01-10,77.0,114.0,False
4,P0229,Patient_P0229,1987-07-10,2023-01-17,71.0,152.0,False
...,...,...,...,...,...,...,...
2095,P0375,Patient_P0375,1952-04-27,2023-01-08,90.0,119.0,False
2096,P0319,Patient_P0319,1956-12-01,2023-01-19,65.0,175.0,False
2097,P0243,Patient_P0243,1963-03-03,2023-01-23,51.0,153.0,False
2098,P0016,Patient_P0016,1997-08-04,2023-01-20,NaN,129.0,False
2099,P0233,Patient_P0233,1947-11-12,2023-01-10,65.0,125.0,False

### Exercise 5: Flag outliers

In [16]:
# your code goes here

clinical_df_deduped["heart_rate_outlier"] = clinical_df_deduped["heart_rate"] > 180

clinical_df_deduped

,patient_id,patient_name,date_of_birth,visit_date,heart_rate,systolic_bp,heart_rate_outlier
0,P0373,Patient_P0373,1975-01-15,2023-01-18,82.0,132.0,False
1,P0280,Patient_P0280,1957-05-04,2023-01-13,45.0,124.0,False
2,P0228,Patient_P0228,1971-06-17,2023-01-09,54.0,108.0,False
3,P0196,Patient_P0196,1982-12-19,2023-01-10,77.0,114.0,False
4,P0229,Patient_P0229,1987-07-10,2023-01-17,71.0,152.0,False
...,...,...,...,...,...,...,...
2095,P0375,Patient_P0375,1952-04-27,2023-01-08,90.0,119.0,False
2096,P0319,Patient_P0319,1956-12-01,2023-01-19,65.0,175.0,False
2097,P0243,Patient_P0243,1963-03-03,2023-01-23,51.0,153.0,False
2098,P0016,Patient_P0016,1997-08-04,2023-01-20,NaN,129.0,False
2099,P0233,Patient_P0233,1947-11-12,2023-01-10,65.0,125.0,False

### Exercise 6: De-identify the dataset

In [17]:
# your code goes here

# Drop direct identifiers
deidentified_df = clinical_df_deduped.drop(columns=["patient_name"])

# Generalize dates to year only
deidentified_df["birth_year"] = deidentified_df["date_of_birth"].dt.year
deidentified_df["visit_year"] = deidentified_df["visit_date"].dt.year

# Drop original date columns
deidentified_df = deidentified_df.drop(columns=["date_of_birth", "visit_date"])

deidentified_df

,patient_id,heart_rate,systolic_bp,heart_rate_outlier,birth_year,visit_year
0,P0373,82.0,132.0,False,1975,2023
1,P0280,45.0,124.0,False,1957,2023
2,P0228,54.0,108.0,False,1971,2023
3,P0196,77.0,114.0,False,1982,2023
4,P0229,71.0,152.0,False,1987,2023
...,...,...,...,...,...,...
2095,P0375,90.0,119.0,False,1952,2023
2096,P0319,65.0,175.0,False,1956,2023
2097,P0243,51.0,153.0,False,1963,2023
2098,P0016,NaN,129.0,False,1997,2023
2099,P0233,65.0,125.0,False,1947,2023